# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmFw4Io8OZmEpn1PYZ17xt4rUDIbKTMA
"""

print("morra ou lute")

nome = input("qual seu nome: ")
print("bem vindo: " , nome)

print("vc encontrou um inimigo:")

print("1 - lutar")
print("2 - fugir")

ik = input("oq vc vai fazer: ")

if ik == "1":
    print("escolha oq vai ser")
    print("1 - Guarreiro")
    print("2 - mago")
    oo = input("escolha rapido: ")
    if oo == "1":
      print("vc venceu seu inimigo com um unico golpe de espada")
    elif oo == "2":
      print("Seu inimigo correu amedrontado")


elif ik == "2":
    print("o jogo acabou")
else:
   print("operação invalida")


input('pressione ENTER pra sair...')